<?php
declare(strict_types=1);

namespace CakeDC\Forum;

use Cake\Core\BasePlugin;
use Cake\Core\Configure;
use Cake\Core\PluginApplicationInterface;
use Cake\Http\MiddlewareQueue;
use Cake\Utility\Hash;

/**
 * Plugin for Forup
 */
class Plugin extends BasePlugin
{
    /**
     * @inheritDoc
     */
    public function bootstrap(PluginApplicationInterface $app): void
    {
        $app->addPlugin('Muffin/Slug');
        $app->addPlugin('Muffin/Orderly');

        $this->setupGlobalConfig();
    }

    /**
     * @inheritDoc
     */
    public function middleware(MiddlewareQueue $middleware): MiddlewareQueue
    {
        return parent::middleware($middleware); // TODO: Change the autogenerated stub
    }

    /**
     * Setup global config for this plugin. Values are set at
     * Forum key using Cake\Core\Configure class
     *
     * @return void
     */
    protected function setupGlobalConfig(): void
    {
        $defaults = [
            // User model name
            'userModel' => 'Users',
            // Name field in user model to display in forum template
            'userNameField' => 'full_name',
            // User profile url (false, array or callable). Username will be displayed with no link if FALSE
            'userProfileUrl' => false,
            // Posts count field in User model for CounterCache behavior. Not used if FALSE
            'userPostsCountField' => false,
            // Function for messages rendering in forum templates
            'messageRenderer' => function (string $message): string {
                return nl2br(h($message));
            },
            // Field name or callable function to check if user is has access to admin interface
            'adminCheck' => 'is_superuser',
            // Threads limit per page
            'threadsPerPage' => 20,
            // Posts limit per page
            'postsPerPage' => 20,
        ];
        $config = Hash::merge($defaults, (array)Configure::read('Forum'));
        Configure::write('Forum', $config);
    }
}
