<?php
declare(strict_types=1);

namespace CakeDC\Forum;

use Cake\Core\BasePlugin;
use Cake\Core\PluginApplicationInterface;
use Cake\Http\MiddlewareQueue;
use Cake\Routing\RouteBuilder;

/**
 * Plugin for Forup
 */
class Plugin extends BasePlugin
{
    /**
     * @inheritDoc
     */
    public function bootstrap(PluginApplicationInterface $app): void
    {
        $app->addPlugin('Muffin/Slug');
        $app->addPlugin('Muffin/Orderly');

        parent::bootstrap($app);
    }

    /**
     * @inheritDoc
     */
    public function middleware(MiddlewareQueue $middleware): MiddlewareQueue
    {
        return parent::middleware($middleware); // TODO: Change the autogenerated stub
    }

}
